FROM python:3.13.3-slim-bullseye

ENV PYTHONUNBUFFERED True

# set the working directory
WORKDIR /code

# install dependencies
COPY ./requirements /code/requirements/

RUN pip install --no-cache-dir --upgrade -r /code/requirements/requirements.txt

# copy src code
COPY ./app /code/app

EXPOSE 80

# start the server
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80", "--proxy-headers"]