FROM python:3.11-slim-bullseye

ENV PYTHONUNBUFFERED 1

WORKDIR /code

COPY ./requirements /code/requirements

RUN pip install --no-cache-dir --upgrade -r /code/requirements/requirements.txt

COPY ./app /code/app

EXPOSE 8080

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8080", "--proxy-headers"]