FROM python:3.11-slim-bullseye

ENV PYTHONUNBUFFERED True

# set the working directory
WORKDIR /code

# install dependencies
COPY ./requirements /code/requirements/

RUN pip install --no-cache-dir --upgrade -r /code/requirements/requirements.txt

# copy src code
COPY . /code/

EXPOSE 8080

# start the server
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8080", "--proxy-headers"]